# Form implementation generated from reading ui file 'premediaapp.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(764, 669)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("premedia.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        Dialog.setWindowIcon(icon)
        Dialog.setStyleSheet("/* ===============================\n"
"🌐 Base Form Style (Clean/Neutral)\n"
"================================== */\n"
"QDialog, QWidget {\n"
"    background-color: #f4f6f8;  /* light neutral background */\n"
"    font-family: \"Segoe UI\", \"Helvetica Neue\", sans-serif;\n"
"    font-size: 14px;\n"
"    color: #333333;\n"
"}\n"
"\n"
"/* ===============================\n"
"🖼️ QLabel Styling\n"
"================================== */\n"
"QLabel {\n"
"    background-color: transparent;\n"
"    font-size: 13px;\n"
"    color: #2e2e2e;\n"
"}\n"
"\n"
"QLabel#label_2,\n"
"QLabel#label_3 {\n"
"    background-color: #e0e0e0;\n"
"    padding: 6px 10px;\n"
"    border-radius: 0px 5px 0px 5px;\n"
"    font-weight: 500;\n"
"    color: #1a1a1a;\n"
"}\n"
"\n"
"QLabel#label {\n"
"    qproperty-alignment: AlignCenter;\n"
"    padding: 10px;\n"
"}\n"
"\n"
"/* ===============================\n"
"📦 QGroupBox Styling\n"
"================================== */\n"
"QGroupBox {\n"
"    background-color: #ffffff;\n"
"    border: 1px solid #d1d1d1;\n"
"    border-radius: 10px;\n"
"    padding: 20px;\n"
"    margin-top: 10px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QGroupBox::title {\n"
"    subcontrol-origin: content;\n"
"    subcontrol-position: top left;\n"
"    margin-top: -12px;\n"
"    padding: 4px 10px;\n"
"    font-size: 15px;\n"
"    color: #0078d7;\n"
"}\n"
"\n"
"/* ===============================\n"
"🔤 QLineEdit (Inputs)\n"
"================================== */\n"
"QLineEdit {\n"
"    background-color: #ffffff;\n"
"    border: 1px solid #bfc5ca;\n"
"    border-radius: 6px;\n"
"    padding: 8px 12px;\n"
"    font-size: 13px;\n"
"    color: #333;\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 1px solid #0078d7;\n"
"    background-color: #f0faff;\n"
"}\n"
"\n"
"/* ===============================\n"
"✅ QCheckBox with Clean Label Background\n"
"================================== */\n"
"QCheckBox {\n"
"    spacing: 6px;\n"
"    font-size: 13px;\n"
"    color: #1a1a1a;\n"
"    padding: 6px 8px;\n"
"    border-radius: 6px;\n"
"    background-color: #eeeeee;\n"
"}\n"
"\n"
"QCheckBox::indicator {\n"
"    width: 16px;\n"
"    height: 16px;\n"
"    border-radius: 3px;\n"
"    border: 1px solid #999;\n"
"    background-color: #ffffff;\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"    background-color: #0078d7;\n"
"    image: none;\n"
"}\n"
"\n"
"QCheckBox::indicator:hover {\n"
"    border: 1px solid #3399ff;\n"
"}\n"
"\n"
"/* ===============================\n"
"🔘 QRadioButton Styling\n"
"================================== */\n"
"QRadioButton {\n"
"    spacing: 6px;\n"
"    font-size: 13px;\n"
"    color: #2e2e2e;\n"
"    padding: 6px 8px;\n"
"}\n"
"\n"
"QRadioButton::indicator {\n"
"    width: 16px;\n"
"    height: 16px;\n"
"    border-radius: 8px;\n"
"    border: 2px solid #0078d7;\n"
"    background-color: white;\n"
"}\n"
"\n"
"QRadioButton::indicator:checked {\n"
"    background-color: #0078d7;\n"
"}\n"
"\n"
"QRadioButton::indicator:unchecked {\n"
"    background-color: white;\n"
"    border: 2px solid #bbb;\n"
"}\n"
"\n"
"/* ===============================\n"
"🧩 QPushButton Styling (Flat & Modern)\n"
"================================== */\n"
"QPushButton {\n"
"    background-color: #0078d7;\n"
"    color: white;\n"
"    padding: 8px 16px;\n"
"    border-radius: 5px;\n"
"    font-weight: bold;\n"
"    min-width: 90px;\n"
"    min-height: 30px;\n"
"    border: none;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #005a9e;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #004578;\n"
"}\n"
"\n"
"/* ===============================\n"
"💬 QDialogButtonBox Buttons\n"
"================================== */\n"
"QDialogButtonBox QPushButton {\n"
"    background-color: #0078d7;\n"
"    color: white;\n"
"    padding: 8px 16px;\n"
"    border-radius: 5px;\n"
"    font-weight: bold;\n"
"    border: none;\n"
"    min-width: 90px;\n"
"    min-height: 30px;\n"
"}\n"
"\n"
"QDialogButtonBox QPushButton:hover {\n"
"    background-color: #005a9e;\n"
"}\n"
"\n"
"QDialogButtonBox QPushButton:pressed {\n"
"    background-color: #004578;\n"
"}\n"
"")
        self.groupBox = QtWidgets.QGroupBox(parent=Dialog)
        self.groupBox.setGeometry(QtCore.QRect(60, 130, 631, 461))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.label_3 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(90, 200, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(63)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.lineEdit = QtWidgets.QLineEdit(parent=self.groupBox)
        self.lineEdit.setGeometry(QtCore.QRect(80, 120, 441, 61))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(-1)
        self.lineEdit.setFont(font)
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(parent=self.groupBox)
        self.lineEdit_2.setGeometry(QtCore.QRect(80, 230, 441, 61))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(-1)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.checkBox = QtWidgets.QCheckBox(parent=self.groupBox)
        self.checkBox.setGeometry(QtCore.QRect(80, 310, 181, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(-1)
        self.checkBox.setFont(font)
        self.checkBox.setObjectName("checkBox")
        self.label_2 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(90, 90, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(63)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=self.groupBox)
        self.buttonBox.setGeometry(QtCore.QRect(350, 370, 251, 61))
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.label = QtWidgets.QLabel(parent=Dialog)
        self.label.setGeometry(QtCore.QRect(240, 10, 271, 121))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("vmg-premedia-logo.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")

        self.retranslateUi(Dialog)
        self.buttonBox.rejected.connect(Dialog.reject) # type: ignore
        self.buttonBox.accepted.connect(Dialog.accept) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.groupBox.setTitle(_translate("Dialog", "LOGIN"))
        self.label_3.setText(_translate("Dialog", "Enter Password Here"))
        self.lineEdit.setPlaceholderText(_translate("Dialog", "USER EMAIL ID"))
        self.lineEdit_2.setPlaceholderText(_translate("Dialog", "USER PASSWORD"))
        self.checkBox.setText(_translate("Dialog", "Remember Password"))
        self.label_2.setText(_translate("Dialog", "Enter User Name Here"))
